name: Deployment notifications
description: 'Notification Slack pour les déploiement'
inputs:
  status:
    required: true
    description: "Status de la notification (success/failure)"
  environment:
    required: true
    description: "Environnement du déploiement"
  slack_webhook:
    required: true
    description: "URL du webhook Slack"
runs:
  using: "composite"
  steps:
  - uses: slackapi/slack-github-action@v2.0.0
    with:
      webhook: ${{ inputs.slack_webhook }}
      webhook-type: incoming-webhook
      payload: |
        attachments:
        - color: ${{ inputs.status == 'success' && '#7ed07e' || '#ac3d00' }}
          blocks:
          - type: section
            text:
              type: mrkdwn
              text: |-
                ${{ inputs.status == 'success' && 'Succès' || 'Erreur' }} du Déploiement du projet <${{ github.server_url }}/${{ github.repository }}|*${{ github.repository }}*> sur ${{inputs.environment}}
          - type: divider
          - type: rich_text
            elements:
            - type: rich_text_list
              style: bullet
              elements:
              - type: rich_text_section
                elements:
                - type: link
                  url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  text: Github Actions
