name: Deploy on Prod

on:
  workflow_call:
    inputs:
      product:
        required: true
        type: string
        description: "Nom du produit"
      version:
        required: true
        type: string
        description: "Version à déployer (SHA commit ou Tag)"
    secrets:
      gcp_provider_id:
        required: true
        description: "ID du provider GCP"
      gcp_service_account:
        required: true
        description: "Nom du compte de service GCP"
      slack_webhook:
        required: true
        description: "URL du webhook Slack"

jobs:
  prod:
    uses: ./.github/workflows/deploy.yml
    with:     
      product: ${{ inputs.product }}
      version: ${{ inputs.version }}
      environment: prod
      cluster_name: prod
      cluster_zone: europe-west3-c
      cluster_project: cozynergy-prod
    secrets:
      gcp_provider_id: ${{ secrets.gcp_provider_id }}
      gcp_service_account: ${{ secrets.gcp_service_account }}
      slack_webhook: ${{ secrets.slack_webhook }}
