name: Deploy on Prod

on:
  workflow_call:
    inputs:
      product:
        required: true
        type: string
        description: "Nom du produit"
      version:
        required: true
        type: string
        description: "Version à déployer (SHA commit ou Tag)"

jobs:
  prod:
    uses: ./.github/workflows/deploy.yml
    with:     
      product: ${{ inputs.product }}
      version: ${{ inputs.version }}
      environment: prod
      cluster_name: prod
      cluster_zone: europe-west3-c
      cluster_project: cozynergy-prod
    secrets: inherit
