name: Pull Request notifications
on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
        description: "Status de la notification (success/failure)"

jobs:
  notify:
    runs-on: cozynergy
    steps:
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          errors: true
          payload: |
            channel: C02B0FGFG3X
            text: "Hello from seprate worflow"
