name: Pull Request notifications
on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
        description: "Status de la notification (success/failure)"

jobs:
  notify:
    runs-on: cozynergy
    steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{secrets.SLACK_TEST_WEBHOOK_URL}}
        webhook-type: incoming-webhook
        payload: |
          text: "Greetings!"